# Generated by Django 4.1 on 2022-08-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimg', models.ImageField(null=True, upload_to='')),
                ('pname', models.CharField(max_length=200)),
                ('ptype', models.CharField(choices=[(1, '蔬菜'), (2, '水果'), (3, '肉類'), (4, '蛋類')], max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
