# Generated by Django 4.1 on 2022-08-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='ptype',
            field=models.CharField(choices=[('蔬菜', '蔬菜'), ('水果', '水果'), ('肉類', '肉類'), ('蛋類', '蛋類')], max_length=200),
        ),
    ]
