# Generated by Django 4.1 on 2022-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketWebsite', '0002_alter_production_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='pimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
