# Generated by Django 4.1 on 2022-08-19 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketWebsite', '0003_alter_production_pimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 19, 4, 9, 6, 25664, tzinfo=datetime.timezone.utc)),
        ),
    ]
