# Generated by Django 4.1 on 2022-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketWebsite', '0004_alter_production_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
